WIP Adds MVC and migrations for package test loads.
sul-dlss/libsys-webforms pull request #592
Opened 2018-11-22 00:32 UTC by shelleydoljack

Fixes #574 
Fixes #588

2018-12-19 21:28 UTC, shelleydoljack commented
@jgreben ready for review and merge.

2018-12-19 21:40 UTC, shelleydoljack commented
Related shared_configs PRs:
https://github.com/sul-dlss/shared_configs/pull/765
https://github.com/sul-dlss/shared_configs/pull/795

2019-01-07 18:53 UTC, jgreben requested changes

2019-01-07 18:53 UTC, jgreben commented on config/routes.rb
> +    if Rails.env.development? || Rails.env.test?
See if you can remove these routing conditions and handle it all with can-can + the pl/sql settings user permissions?

2019-01-07 18:53 UTC, jgreben commented on config/routes.rb
> +  if Rails.env.development? || Rails.env.test?
Same as above

2019-01-08 18:57 UTC, jgreben approved these changes

2019-01-08 18:58 UTC, merged